    <div id='entries' style='display:none'>
<?php foreach ($this->entries as $entry): ?>
        <div class='item'>
<?php echo $entry['comment'] ?>
            <div class='meta'><?php echo $this->escape($entry['Creator']['username']) ?> - <?php echo $entry['modified'] ?></div>
        </div>
<?php endforeach ?>
    </div>
    <script>
        var contacts = <?php echo Zend_Json::encode($this->users) ?>;
        var discussions = <?php echo Zend_Json::encode($this->discussions) ?>;

        function flatten(obj) {
            var propSet = [];
            for (var i in obj) {
                if ('object' == typeof obj[i] && null != obj[i]) {
                    var subPropSet = flatten(obj[i]);
                    for (var si in subPropSet) {
                        propSet[i + '_' + si] = subPropSet[si];
                    }
                } else {
                    propSet[i] = (obj[i]);
                }
            }
            return propSet;
        }

        for (var i in discussions) {
            discussions[i] = flatten(discussions[i]);
        }
    </script>
    <script src='/app/js/wave-theme.js'></script>
    <script src='/app/js/wave.js'></script>
