<h1>REST Example Application</h1>

<h2>Regular HTML Page</h2>
<ul>
    <li><a href="/entry">entry</a></li>
</ul>

<h2>API Examples</h2>
<ul>
    <li><a href="/api/entry/">all entries</a></li>
    <li><a href="/api/user/">all users</a></li>
    <li><a href="/api/email/">all emails</a></li>
    <li><a href="/api/entry/?entourage=Creator">entries with creator user information</a></li>
    <li><a href="/api/user/?entourage=Entry">users with entries of that user attached</a></li>
    <li><a href="/api/user/?entourage[]=Entry&entourage[]=PrimaryEmail">users with entries and primary email attached</a></li>
</ul>

<h3>Demo User Names and Password</h3>
<ul>
    <li>Alex:Alex</li>
    <li>Bob:Bob</li>
    <li>Carl:Carl</li>
    <li>Dan:Dan</li>
    <li>Ed:Ed</li>
</ul>

<h3>JSON Viewers</h3>
<p>Firebug in Firefox has a JSON viewer. Bring up Firebug and switch to the Net tab, then follow a link above. Click on the loaded entry and switch over to JSON. Enjoy goodness.</p>

<h2>API Tests</h2>
<p>with built in JSON viewer</p>
<ul>
    <li><a href="/test/">tests</a></li>
</ul>
