<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>REST App Example</title>
    <?php echo $this->headLink()->appendStylesheet('/app/css/style.css') ?>
    <script src="/default/js/jquery-1.4.2.min.js"></script>
    <script src="/app/js/uki-theamless.js"></script>
</head>
<body>

<?php echo $this->layout()->content ?>

</body>
</html>
