<?php echo $this->doctype() ?> <!-- This Line will output the doctype we set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
    <title>REST App Example</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    <script src="/scripts/jquery-1.4.2.min.js"></script>
</head> 
<body>

<?php echo $this->layout()->content ?>

</body>
</html>
