<p><a href="<?php echo $this->url(array('action' => 'sign')) ?>">Sign Our Guestbook</a></p>

Guestbook Entries: <br />
<div class="guestbook">
    <ul>
<!-- Loop through the entries that were provided to us by the controller -->
<?php foreach ($this->data as $entry): ?>
        <li class="entry">
            <div class="id"><?php echo $this->escape($entry['id']) ?></div>
            <div class="comment"><?php echo $this->escape($entry['comment']) ?></div>
            <div class="creator_user_id"><?php echo $this->escape($entry['creator_user_id']) ?></div>
            <div class="creator_name"><?php echo $this->escape($entry['Creator']['name']) ?></div>
            <div class="modified"><?php echo $this->escape($entry['modified']) ?></div>
        </li>
<?php endforeach ?>
    </ul>
</div>

<script src="/scripts/entry/form.js"></script>
<script>

$('.guestbook li.entry')
    .append('<input type="button" class="control control_put" value="Edit"/>')
    .append('<input type="button" class="control control_delete" value="Delete"/>');

$('.guestbook')
    .append('<input type="button" class="control control_post" value="Sign Guestbook"/>');


function refreshEntryFromData(entry, data) {
    $('div.comment', entry).text(data.comment);
    $('div.creator_user_id', entry).text(data.creator_user_id);
    if (data.Creator) {
        $('div.creator_name', entry).text(data.Creator.name);
    } else {
        $.getJSON('/api-user/' + escape(data.creator_user_id), function(data) {
            refreshEntryFromData(data.content);
        });
    }
    $('div.modified', entry).text(data.modified);
}

function refreshEntry(entry, data) {
    if (null != data) {
        refreshEntryFromData(entry, data);
        return;
    }

    $('<div class="loading">loading...</div>').appendTo(entry);

    var id = $('div.id', entry).text();

    $.getJSON('/api-entry/' + escape(id) + '?' + JSON.stringify({'entourage':'Creator'}), function(data) {
        refreshEntryFromData(data.content);
        $('div.loading', entry).remove();
    });
}


$('.guestbook .entry .control_put').live('click', function() {
    var entry = $(this).parent();

    form = $('<div class="form"/>').append(
        application['guestbook.entry.form'](
            $('div.comment', entry).text(),
            'PUT'
        )
    ).appendTo(entry).slideDown();

    $('.cancel', form).click(function() {
        $('.form', entry).slideUp(function() {
            $(this).remove()
        });
    });

    $('.submit', form).click(function() {
        var id = $('div.id', entry).text();
        var data = {
            'comment': $('.comment', form).val()
        };

        var submitButton = $(this);

        $.ajax({
            url: '/api-entry/' + id,
            type: 'PUT',
            data: JSON.stringify(data),
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            beforeSend: function() {
                submitButton.val('Editing...');
            },
            success: function(result) {
                submitButton.val('Edited');
                form.slideUp(function() {
                    $(this).remove();
                });
                refreshEntry(entry, result.content);
            }
        });
    });
});

$('.guestbook .entry .control_delete').live('click', function () {
    var entry = $(this).parent();
    var id = $('div.id', entry).text();

    $.ajax({
        url: '/api-entry/' + id,
        type: 'DELETE',
        dataType: 'json',
        contentType: "application/json; charset=utf-8",
        beforeSend: function() {
            $(this).val('Deleting');
        },
        success: function(result) {
            $(this).val('Deleted');
            entry.slideUp(function() {
                $(this).remove()
            });
        }
    });
});

$('.guestbook .control_post').click(function() {
    var guestbookButton = $(this);
    
    guestbookButton.hide();

    var form = $('<div class="form"/>').append(
        application['guestbook.entry.form']('', 'POST')
    ).hide().insertAfter(this).slideDown();

    $('.cancel', form).click(function() {
        form.slideUp(function() {
            $(this).remove()
        });
        guestbookButton.show();
    });

    $('.submit', form).click(function() {
        var data = {
            'comment': $('.comment', form).val()
        };

        var submitButton = $(this);

        $.ajax({
            url: '/api-entry',
            type: 'POST',
            data: JSON.stringify(data),
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            beforeSend: function() {
                submitButton.val('Signing...');
            },
            success: function(result) {
                submitButton.val('Signed');
                form.slideUp(function() {
                    $(this).remove();
                });
                guestbookButton.show();
                entry = $('<li class="entry"><div class="id"/><div class="comment"/><div class="creator_user_id"/><div class="creator_name"/><div class="modified"/><input type="button" class="control control_put" value="Edit"/><input type="button" class="control control_delete" value="Delete"/></li>');
                refreshEntry(entry, result.content);
                entry.hide().appendTo('div.guestbook ul').slideDown();
            }
        });
    });
});

</script>