<h1>Sign the Guestbook</h1>
<div class="form"></div>

<script src="/scripts/entry/form.js"></script>
<script>

$(function() {
    var form = $('.form').append(
        application['guestbook.entry.form']('', 'POST')
    );

    $('.cancel', form).click(function() {
        window.location = '/entry';
    });

    $('.submit', form).click(function() {
        var data = {
            'comment': $('.comment', form).val()
        };

        var submitButton = $(this);

        $.ajax({
            url: '/entry-api',
            type: 'POST',
            data: JSON.stringify(data),
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            beforeSend: function() {
                submitButton.val('Signing...');
            },
            success: function(result) {
                submitButton.val('Signed');
                window.location = '/entry';
            }
        });
    });
});

</script>